# Generated by Django 4.1.7 on 2023-03-18 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "phase_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LP0", "Other"),
                            ("LP1", "Feasibility study"),
                            ("LP2", "Preliminary design"),
                            ("LP3", "Definitive design"),
                            ("LP4", "Authoring"),
                            ("LP5", "Construction design"),
                            ("LP6", "Tender design"),
                            ("LP7", "Project management"),
                            ("LP8", "Construction supervision"),
                            ("LP9", "Maintenance design"),
                        ],
                        max_length=4,
                        null=True,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("start", models.DateField(blank=True, null=True)),
                ("duration", models.PositiveIntegerField(default=1)),
                ("delay", models.IntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="timeline.phase",
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phase",
                "verbose_name_plural": "Phases",
                "ordering": ["position"],
            },
        ),
    ]
