# Generated by Django 4.1.7 on 2023-03-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulktable", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="row",
            name="color",
            field=models.CharField(
                choices=[
                    ("light", "White"),
                    ("danger", "Red"),
                    ("success", "Green"),
                    ("primary", "Blue"),
                    ("warning", "Yellow"),
                ],
                max_length=7,
            ),
        ),
    ]
